import type { Risk } from "@/types/risk";

export const sampleRisks: Risk[] = [
  {
    id: "R-001",
    title: "عدم تفعيل المصادقة متعددة العوامل",
    description: "اعتماد بعض الحسابات الحساسة على كلمة مرور فقط يزيد احتمالية الوصول غير المصرح.",
    category: "الوصول والهوية",
    asset: "حسابات الموظفين والأنظمة الداخلية",
    threat: "سرقة بيانات الدخول أو التصيد الاحتيالي",
    vulnerability: "غياب MFA للحسابات الحساسة",
    likelihood: 4,
    impact: 5,
    score: 20,
    level: "حرج",
    owner: "مسؤول أمن المعلومات",
    department: "تقنية المعلومات",
    mitigationPlan: "تفعيل MFA للحسابات الحساسة، ومراجعة الحسابات عالية الصلاحية، وتوعية المستخدمين.",
    control: "إدارة الهوية والمصادقة",
    frameworkRef: "NIST SP 800-53: IA-2, AC-2",
    csfFunction: "Protect",
    treatment: "تخفيف",
    status: "قيد المعالجة",
    dueDate: "2026-06-15",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  },
  {
    id: "R-002",
    title: "تأخر تحديث الأنظمة",
    description: "وجود أنظمة غير محدثة قد يرفع احتمالية استغلال الثغرات المعروفة.",
    category: "إدارة الثغرات",
    asset: "الخوادم وأجهزة المستخدمين",
    threat: "استغلال ثغرات معروفة",
    vulnerability: "غياب جدول تحديثات واضح",
    likelihood: 4,
    impact: 4,
    score: 16,
    level: "حرج",
    owner: "فريق البنية التحتية",
    department: "تقنية المعلومات",
    mitigationPlan: "إنشاء Patch Management Schedule، وترتيب التحديثات حسب درجة الخطورة، ومتابعة الالتزام شهريًا.",
    control: "إدارة التحديثات والثغرات",
    frameworkRef: "NIST SP 800-53: SI-2, RA-5",
    csfFunction: "Identify",
    treatment: "تخفيف",
    status: "مفتوح",
    dueDate: "2026-06-01",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  },
  {
    id: "R-003",
    title: "ضعف الوعي الأمني ضد رسائل التصيد",
    description: "قلة تدريب الموظفين قد تؤدي إلى فتح روابط أو مرفقات ضارة.",
    category: "التوعية الأمنية",
    asset: "البريد الإلكتروني وحسابات المستخدمين",
    threat: "Phishing",
    vulnerability: "غياب قياس دوري للوعي الأمني",
    likelihood: 5,
    impact: 3,
    score: 15,
    level: "عالي",
    owner: "فريق التوعية الأمنية",
    department: "الموارد البشرية وتقنية المعلومات",
    mitigationPlan: "إطلاق برنامج توعوي ربع سنوي، واختبارات قصيرة، وحملة محاكاة تصيد آمنة.",
    control: "التوعية والتدريب",
    frameworkRef: "NIST SP 800-53: AT-2",
    csfFunction: "Protect",
    treatment: "تخفيف",
    status: "قيد المعالجة",
    dueDate: "2026-07-01",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  },
  {
    id: "R-004",
    title: "صلاحيات مستخدمين أعلى من الحاجة",
    description: "امتلاك بعض المستخدمين صلاحيات لا تتناسب مع مهامهم يزيد أثر أي خطأ أو اختراق.",
    category: "الوصول والهوية",
    asset: "أنظمة الأعمال وقواعد البيانات",
    threat: "إساءة استخدام الصلاحيات أو اختراق حساب مميز",
    vulnerability: "عدم وجود مراجعة دورية للصلاحيات",
    likelihood: 3,
    impact: 5,
    score: 15,
    level: "عالي",
    owner: "مدير الأنظمة",
    department: "تقنية المعلومات",
    mitigationPlan: "تطبيق مبدأ أقل صلاحية، وجدولة Access Review شهرية للحسابات الحساسة.",
    control: "إدارة الصلاحيات",
    frameworkRef: "NIST SP 800-53: AC-6, AC-2",
    csfFunction: "Govern",
    treatment: "تخفيف",
    status: "مفتوح",
    dueDate: "2026-06-25",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  },
  {
    id: "R-005",
    title: "عدم اختبار النسخ الاحتياطية",
    description: "قد تكون النسخ الاحتياطية موجودة لكنها غير قابلة للاستعادة وقت الحاجة.",
    category: "استمرارية الأعمال",
    asset: "البيانات التشغيلية",
    threat: "فقدان بيانات أو فشل استعادة",
    vulnerability: "عدم اختبار الاستعادة بشكل دوري",
    likelihood: 3,
    impact: 5,
    score: 15,
    level: "عالي",
    owner: "فريق البنية التحتية",
    department: "تقنية المعلومات",
    mitigationPlan: "تنفيذ اختبار استعادة شهري، وتوثيق نتائج الاختبار، وتحديد زمن الاستعادة المستهدف.",
    control: "النسخ الاحتياطي والاستعادة",
    frameworkRef: "NIST SP 800-53: CP-9, CP-10",
    csfFunction: "Recover",
    treatment: "تخفيف",
    status: "مفتوح",
    dueDate: "2026-06-20",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  },
  {
    id: "R-006",
    title: "إعدادات تخزين سحابي غير آمنة",
    description: "الإعدادات الخاطئة قد تسمح بوصول عام إلى ملفات داخلية أو بيانات حساسة.",
    category: "الأمن السحابي",
    asset: "مجلدات التخزين السحابي",
    threat: "تسريب بيانات",
    vulnerability: "عدم مراجعة إعدادات المشاركة والخصوصية",
    likelihood: 3,
    impact: 4,
    score: 12,
    level: "عالي",
    owner: "مسؤول الأنظمة السحابية",
    department: "تقنية المعلومات",
    mitigationPlan: "مراجعة إعدادات المشاركة، وتقييد الوصول العام، وتفعيل تنبيهات الملفات الحساسة.",
    control: "إعدادات الحماية السحابية",
    frameworkRef: "NIST SP 800-53: AC-3, SC-7",
    csfFunction: "Protect",
    treatment: "تخفيف",
    status: "قيد المعالجة",
    dueDate: "2026-06-30",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  },
  {
    id: "R-007",
    title: "غياب خطة استجابة للحوادث",
    description: "عدم وجود خطة واضحة قد يؤخر الاحتواء والتواصل وقت وقوع حادث أمني.",
    category: "الاستجابة للحوادث",
    asset: "فرق التشغيل والأمن",
    threat: "تأخر الاستجابة أو ضعف التنسيق",
    vulnerability: "غياب أدوار ومسؤوليات موثقة",
    likelihood: 3,
    impact: 4,
    score: 12,
    level: "عالي",
    owner: "قائد الأمن السيبراني",
    department: "الأمن السيبراني",
    mitigationPlan: "إعداد Incident Response Plan، وتحديد أدوار الفريق، وتنفيذ تمرين Tabletop.",
    control: "إدارة الاستجابة للحوادث",
    frameworkRef: "NIST SP 800-53: IR-4, IR-8",
    csfFunction: "Respond",
    treatment: "تخفيف",
    status: "مفتوح",
    dueDate: "2026-07-10",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  },
  {
    id: "R-008",
    title: "عدم اكتمال جرد الأصول التقنية",
    description: "عدم معرفة كل الأصول يجعل تقييم المخاطر والتحديثات والمتابعة أقل دقة.",
    category: "إدارة الأصول",
    asset: "الأجهزة والتطبيقات والخدمات",
    threat: "أصول غير مراقبة أو غير محدثة",
    vulnerability: "غياب سجل أصول محدث",
    likelihood: 4,
    impact: 3,
    score: 12,
    level: "عالي",
    owner: "مدير تقنية المعلومات",
    department: "تقنية المعلومات",
    mitigationPlan: "بناء Asset Inventory وتحديثه شهريًا وربطه بعملية إدارة التغيير.",
    control: "إدارة الأصول والتكوين",
    frameworkRef: "NIST SP 800-53: CM-8, CM-2",
    csfFunction: "Identify",
    treatment: "تخفيف",
    status: "قيد المعالجة",
    dueDate: "2026-06-18",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  },
  {
    id: "R-009",
    title: "مخاطر الطرف الثالث",
    description: "مقدمو الخدمات قد يعالجون بيانات أو يملكون وصولًا يحتاج إلى تقييم ومتابعة.",
    category: "الأطراف الخارجية",
    asset: "العقود والتكاملات الخارجية",
    threat: "ضعف ضوابط مقدم الخدمة",
    vulnerability: "غياب تقييم أمني للموردين",
    likelihood: 3,
    impact: 4,
    score: 12,
    level: "عالي",
    owner: "إدارة المشتريات والأمن السيبراني",
    department: "المشتريات",
    mitigationPlan: "إضافة استبيان تقييم أمني للموردين، ومراجعة عقود الوصول والسرية قبل التعاقد.",
    control: "إدارة مخاطر الموردين",
    frameworkRef: "NIST SP 800-53: SR-3, SR-6",
    csfFunction: "Govern",
    treatment: "تخفيف",
    status: "مفتوح",
    dueDate: "2026-07-15",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  },
  {
    id: "R-010",
    title: "قواعد جدار ناري قديمة",
    description: "وجود قواعد قديمة أو غير مستخدمة قد يزيد سطح الهجوم أو يسمح بوصول غير ضروري.",
    category: "أمن الشبكات",
    asset: "جدار الحماية والشبكات الداخلية",
    threat: "وصول شبكي غير مصرح",
    vulnerability: "عدم مراجعة القواعد دوريًا",
    likelihood: 2,
    impact: 4,
    score: 8,
    level: "متوسط",
    owner: "مهندس الشبكات",
    department: "الشبكات",
    mitigationPlan: "مراجعة قواعد الجدار الناري ربع سنويًا، وحذف القواعد غير المستخدمة، وتوثيق سبب كل قاعدة.",
    control: "حماية حدود الشبكة",
    frameworkRef: "NIST SP 800-53: SC-7, CM-3",
    csfFunction: "Protect",
    treatment: "تخفيف",
    status: "مغلق",
    dueDate: "2026-05-30",
    createdAt: "2026-05-01",
    updatedAt: "2026-05-07",
  }
];
