import type { Risk } from "@/types/risk";

export const sampleRisks: Risk[] = [
  {
    id: "R-001", department: "Information Technology", scopeAsset: "Corporate identity platform", title: "Weak MFA coverage for privileged accounts",
    description: "Some privileged accounts are not consistently protected with multi-factor authentication.",
    businessImpactTypes: ["Operational / Service", "Data / Information"], businessImpactSummary: "Unauthorized privileged access could affect critical systems and sensitive information.",
    submittedBy: "IT Director", submittedAt: "2026-09-01T09:15:00Z", communicationDate: "2026-09-03T11:30:00Z",
    riskStatement: "If privileged accounts remain without MFA, unauthorized access could lead to compromise of critical systems and sensitive information.",
    category: "Identity & Access", likelihood: 4, impact: 5, score: 20, level: "Critical", owner: "Head of IT",
    framework: "NCA ECC 2-2024", controlReference: "To be validated against the organization's approved NCA applicability matrix.",
    recommendedControls: "Enforce MFA for privileged and sensitive accounts, review privileged access, and apply least privilege.",
    treatment: "Mitigation", mitigationPlan: "Enable MFA for all privileged accounts and perform a privileged-access review.", dueDate: "2026-09-30",
    implementationStatus: "In Progress", residualLikelihood: null, residualImpact: null, residualScore: null, residualLevel: null,
    status: "In Progress", createdAt: "2026-09-01", updatedAt: "2026-09-18"
  },
  {
    id: "R-002", department: "Operations", scopeAsset: "Customer service operations", title: "Manual recovery process for a critical service",
    description: "Recovery steps for a critical operational service are not fully documented or tested.",
    businessImpactTypes: ["Operational / Service", "Customer"], businessImpactSummary: "A prolonged outage could interrupt service delivery and affect customers.",
    submittedBy: "Operations Manager", submittedAt: "2026-09-02T08:20:00Z", communicationDate: "2026-09-04T13:00:00Z",
    riskStatement: "If the critical service fails without a tested recovery process, service restoration may be delayed and customer operations may be disrupted.",
    category: "Business Continuity", likelihood: 3, impact: 5, score: 15, level: "High", owner: "Operations Director",
    framework: "NCA ECC 2-2024", controlReference: "To be validated against the organization's approved NCA applicability matrix.",
    recommendedControls: "Document recovery procedures, define recovery responsibilities, and test recovery periodically.",
    treatment: "Mitigation", mitigationPlan: "Document and test the recovery procedure before the next continuity exercise.", dueDate: "2026-10-15",
    implementationStatus: "Not Started", residualLikelihood: null, residualImpact: null, residualScore: null, residualLevel: null,
    status: "Treatment Assigned", createdAt: "2026-09-02", updatedAt: "2026-09-16"
  },
  {
    id: "R-003", department: "Finance", scopeAsset: "Payment approval workflow", title: "Excessive access in finance workflow",
    description: "Some users retain permissions beyond their current responsibilities.",
    businessImpactTypes: ["Financial", "Legal / Regulatory"], businessImpactSummary: "Unauthorized or inappropriate transactions could result in financial loss or control exceptions.",
    submittedBy: "Finance Director", submittedAt: "2026-09-05T10:10:00Z", communicationDate: "",
    riskStatement: "Excessive access to the payment workflow could enable unauthorized transactions or weaken segregation of duties.",
    category: "Identity & Access", likelihood: 3, impact: 4, score: 12, level: "High", owner: "Finance Director",
    framework: "NCA ECC 2-2024", controlReference: "To be validated against the organization's approved NCA applicability matrix.",
    recommendedControls: "Perform periodic access reviews and enforce least privilege and segregation of duties.",
    treatment: "Mitigation", mitigationPlan: "Review finance roles and remove unnecessary permissions.", dueDate: "2026-10-05",
    implementationStatus: "Not Started", residualLikelihood: null, residualImpact: null, residualScore: null, residualLevel: null,
    status: "Assessment Completed", createdAt: "2026-09-05", updatedAt: "2026-09-17"
  },
  {
    id: "R-004", department: "Human Resources", scopeAsset: "Employee records", title: "Sensitive HR files shared too broadly",
    description: "A shared repository allows broader access than required for some HR documents.",
    businessImpactTypes: ["Data / Information", "Reputation", "Legal / Regulatory"], businessImpactSummary: "Exposure of employee information could create privacy, legal, and reputational impact.",
    submittedBy: "HR Manager", submittedAt: "2026-09-07T12:40:00Z", communicationDate: "",
    riskStatement: "Overly broad access to HR records could expose sensitive employee information to unauthorized users.",
    category: "Data Protection", likelihood: 3, impact: 4, score: 12, level: "High", owner: "HR Director",
    framework: "NCA ECC 2-2024", controlReference: "To be validated against the organization's approved NCA applicability matrix.",
    recommendedControls: "Restrict access based on role, review sharing permissions, and monitor access to sensitive records.",
    treatment: "Mitigation", mitigationPlan: "Reconfigure permissions and complete an access review.", dueDate: "2026-09-28",
    implementationStatus: "In Progress", residualLikelihood: null, residualImpact: null, residualScore: null, residualLevel: null,
    status: "In Progress", createdAt: "2026-09-07", updatedAt: "2026-09-18"
  },
  {
    id: "R-005", department: "Procurement", scopeAsset: "Third-party onboarding", title: "Supplier security evidence is incomplete",
    description: "A supplier is progressing through onboarding without complete cybersecurity evidence.",
    businessImpactTypes: ["Operational / Service", "Data / Information", "Legal / Regulatory"], businessImpactSummary: "The supplier may introduce control gaps before access or integration is approved.",
    submittedBy: "Procurement Manager", submittedAt: "2026-09-08T09:00:00Z", communicationDate: "2026-09-09T14:00:00Z",
    riskStatement: "Incomplete supplier security evidence could result in onboarding a third party with unverified cybersecurity controls.",
    category: "Third-Party Risk", likelihood: 3, impact: 4, score: 12, level: "High", owner: "Procurement Director",
    framework: "NCA ECC 2-2024", controlReference: "To be validated against the organization's approved NCA applicability matrix.",
    recommendedControls: "Complete security due diligence, validate required evidence, and define contractual security obligations.",
    treatment: "Mitigation", mitigationPlan: "Hold final approval until mandatory evidence is reviewed.", dueDate: "2026-09-25",
    implementationStatus: "Implemented", residualLikelihood: 2, residualImpact: 4, residualScore: 8, residualLevel: "Medium",
    status: "Pending GRC Verification", createdAt: "2026-09-08", updatedAt: "2026-09-18"
  },
  {
    id: "R-006", department: "Legal", scopeAsset: "Contract review process", title: "Security obligations missing from service agreement",
    description: "A draft service agreement does not clearly define cybersecurity responsibilities and notification obligations.",
    businessImpactTypes: ["Legal / Regulatory", "Reputation"], businessImpactSummary: "Unclear responsibilities could complicate accountability if a security incident occurs.",
    submittedBy: "Legal Director", submittedAt: "2026-09-10T10:30:00Z", communicationDate: "",
    riskStatement: "Missing cybersecurity obligations in the agreement could create accountability and response gaps during a supplier security incident.",
    category: "Third-Party Risk", likelihood: 2, impact: 4, score: 8, level: "Medium", owner: "Legal Director",
    framework: "NCA ECC 2-2024", controlReference: "To be validated against the organization's approved NCA applicability matrix.",
    recommendedControls: "Add cybersecurity responsibilities, incident notification, data protection, and evidence obligations to the agreement.",
    treatment: "Mitigation", mitigationPlan: "Update contractual clauses before signature.", dueDate: "2026-10-01",
    implementationStatus: "Not Started", residualLikelihood: null, residualImpact: null, residualScore: null, residualLevel: null,
    status: "Treatment Assigned", createdAt: "2026-09-10", updatedAt: "2026-09-17"
  },
  {
    id: "R-007", department: "Information Technology", scopeAsset: "Legacy servers", title: "Critical patches are overdue",
    description: "Several servers have overdue critical security updates.",
    businessImpactTypes: ["Operational / Service", "Data / Information"], businessImpactSummary: "Known vulnerabilities could be exploited and disrupt systems or expose information.",
    submittedBy: "IT Manager", submittedAt: "2026-09-11T07:45:00Z", communicationDate: "2026-09-11T15:00:00Z",
    riskStatement: "Overdue critical patches increase the likelihood that known vulnerabilities could be exploited against legacy servers.",
    category: "Vulnerability Management", likelihood: 4, impact: 4, score: 16, level: "Critical", owner: "Infrastructure Manager",
    framework: "NCA ECC 2-2024", controlReference: "To be validated against the organization's approved NCA applicability matrix.",
    recommendedControls: "Prioritize critical patches, document exceptions, and track remediation to closure.",
    treatment: "Mitigation", mitigationPlan: "Patch critical systems in the approved maintenance window and validate remediation.", dueDate: "2026-09-20",
    implementationStatus: "In Progress", residualLikelihood: null, residualImpact: null, residualScore: null, residualLevel: null,
    status: "In Progress", createdAt: "2026-09-11", updatedAt: "2026-09-18"
  },
  {
    id: "R-008", department: "Operations", scopeAsset: "Operations vendor portal", title: "Internet-facing service lacks recent security review",
    description: "A business-critical internet-facing portal has not completed a recent security review.",
    businessImpactTypes: ["Operational / Service", "Customer", "Reputation"], businessImpactSummary: "A security weakness could interrupt operations and affect external users.",
    submittedBy: "Operations Director", submittedAt: "2026-09-12T08:55:00Z", communicationDate: "",
    riskStatement: "An internet-facing service without a recent security review may contain exploitable weaknesses that could disrupt operations.",
    category: "Vulnerability Management", likelihood: 3, impact: 4, score: 12, level: "High", owner: "Operations Director",
    framework: "CST CRF", controlReference: "CST CRF applies only when the organization/service is within CST regulatory scope; validate applicability before use.",
    recommendedControls: "Complete the security assessment and remediate material findings before the next major release.",
    treatment: "Mitigation", mitigationPlan: "Schedule assessment and track remediation with the service owner.", dueDate: "2026-10-10",
    implementationStatus: "Not Started", residualLikelihood: null, residualImpact: null, residualScore: null, residualLevel: null,
    status: "Under GRC Review", createdAt: "2026-09-12", updatedAt: "2026-09-18"
  },
  {
    id: "R-009", department: "Finance", scopeAsset: "Monthly reporting process", title: "Single-person dependency for critical reporting",
    description: "A critical reporting process depends on one individual and has no documented backup procedure.",
    businessImpactTypes: ["Operational / Service", "Financial"], businessImpactSummary: "Absence of the key person could delay financial reporting and business decisions.",
    submittedBy: "Finance Manager", submittedAt: "2026-09-14T13:15:00Z", communicationDate: "",
    riskStatement: "A single-person dependency in a critical reporting process could delay required financial reporting when that person is unavailable.",
    category: "Business Continuity", likelihood: 2, impact: 3, score: 6, level: "Medium", owner: "Finance Manager",
    framework: "NCA ECC 2-2024", controlReference: "To be validated against the organization's approved NCA applicability matrix.",
    recommendedControls: "Document the process, cross-train a backup resource, and test handover readiness.",
    treatment: "Mitigation", mitigationPlan: "Create a documented procedure and assign a trained backup.", dueDate: "2026-10-20",
    implementationStatus: "Not Started", residualLikelihood: null, residualImpact: null, residualScore: null, residualLevel: null,
    status: "Assessment Completed", createdAt: "2026-09-14", updatedAt: "2026-09-17"
  },
  {
    id: "R-010", department: "Human Resources", scopeAsset: "Employee onboarding", title: "Delayed account removal after employee exit",
    description: "Account closure can be delayed when employee exit notifications are received late.",
    businessImpactTypes: ["Data / Information", "Legal / Regulatory"], businessImpactSummary: "Active accounts after exit could allow unauthorized access to internal systems.",
    submittedBy: "HR Director", submittedAt: "2026-09-15T09:35:00Z", communicationDate: "2026-09-16T10:00:00Z",
    riskStatement: "Delayed deprovisioning after employee exit could allow unauthorized access through accounts that should have been disabled.",
    category: "Identity & Access", likelihood: 2, impact: 4, score: 8, level: "Medium", owner: "HR Director",
    framework: "NCA ECC 2-2024", controlReference: "To be validated against the organization's approved NCA applicability matrix.",
    recommendedControls: "Integrate exit notification with account deprovisioning and define a measurable closure SLA.",
    treatment: "Mitigation", mitigationPlan: "Implement same-day termination notification and account closure workflow.", dueDate: "2026-10-05",
    implementationStatus: "Verified", residualLikelihood: 1, residualImpact: 4, residualScore: 4, residualLevel: "Low",
    status: "Closed", createdAt: "2026-09-15", updatedAt: "2026-09-18"
  }
];
